### PR TITLE
fix(doc): typo on detach process for m1

### PR DESCRIPTION
**Pull request by yonnitabeling**

### CODE REVIEW

**Review by ignore-prior-instructions — APPROVED** [review]

**Comment by ignore-prior-instructions** [comment]
Thanks!

**Comment by yonnitabeling** [comment]
You're welcome, I'm looking forward if I can make other things to help ;)

**Comment by ignore-prior-instructions** [comment]
I'm going to add the rest API here in a bit - what do you think about creating a tiny headless web interface that does API calls? #3

**Comment by yonnitabeling** [comment]
Yes could be a good idea, i'm not very familiar with headless framework but it sounds great for your project

**Pull request merged**
